apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mahmu\Downloads\Software\kompose.exe convert -f docker-compose.deploy.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: charts
  name: charts
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: charts
status:
  loadBalancer: {}
