apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\mahmu\Downloads\Software\kompose.exe convert -f docker-compose.deploy.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: charts
  name: charts
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: charts
    spec:
      containers:
      - image: ass2-project-template_charts
        name: charts
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
