apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mahmu\Downloads\Software\kompose.exe convert -f docker-compose.deploy.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: search
  name: search
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    io.kompose.service: search
status:
  loadBalancer: {}
