---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 3000
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: 0mahmud1/web
        ports:
        - containerPort: 3000