apiVersion: v1
kind: Service
metadata:
  name: images
spec:
  template:
    metadata:
      labels:
        app: images
        version: "1"
    spec:
      containers:
        - name: images
          image: /0mahmud1/ass2-project-template_images
          imagePullPolicy: IfNotPresent